apiVersion: repo-manager.pulpproject.org/v1beta2
kind: Pulp
metadata:
  name: galaxy
spec:
  # These parameters are designed for use with:
  # - Pulp Operator: 1.0.0-beta.3
  #   https://github.com/pulp/pulp-operator/blob/1.0.0-beta.3/README.md
  # - Galaxy NG: 4.9.0
  #   https://github.com/ansible/galaxy_ng/tree/4.9.0

  deployment_type: galaxy

  image: quay.io/pulp/galaxy
  image_version: 4.9.0
  image_web: quay.io/pulp/galaxy-web
  image_web_version: 4.9.0

  admin_password_secret: galaxy-admin-password

  ingress_type: ingress
  ingress_class_name: traefik
  ingress_tls_secret: galaxy-secret-tls
  ingress_host: galaxy.example.com

  file_storage_storage_class: galaxy-file-volume
  file_storage_access_mode: ReadWriteOnce
  file_storage_size: 8Gi

  pulp_settings:
    TOKEN_AUTH_DISABLED: "True"
    GALAXY_FEATURE_FLAGS__ai_deny_index: "True"
    CSRF_TRUSTED_ORIGINS:
      - https://galaxy.example.com

  api:
    replicas: 1
  cache:
    redis_storage_class: galaxy-redis-volume
  content:
    replicas: 1
  database:
    postgres_storage_class: galaxy-database-volume
    postgres_storage_requirements: 8Gi
  web:
    replicas: 1
  worker:
    replicas: 1
